### ISSUE TITLE
can't set custom sound

### ISSUE THREAD

**Issue by zmike** [freaktechnik/notification-sounds#71]
I've tried setting a custom sound (using flac file), but no sound is emitted. It seems that only the default sound is supported?

Using Firefox 74.0 on Windows 10.-

**Comment by freaktechnik** [comment]
Depending on your windows installation it seems Firefox doesn't properly support all audio codecs in the webextension context for external files. However, the default sound is a FLAC too, so that makes little sense...

**Comment by zmike** [comment]
Is there some way I can debug this?

**Comment by freaktechnik** [comment]
I don't recall everything, since it's been a while. You may find related details I had once figured out in the other open issues (like #51 or the [discourse thread](https://discourse.mozilla.org/t/support-notification-sound/23758))

If you are comfortable with dev tools, you can check out https://extensionworkshop.com/documentation/develop/debugging/ which explains the tools to get access to webextension contexts.

The options page tells the background page to make an audio element and set the source to the file you loaded and play it, see the code path starting at https://github.com/freaktechnik/notification-sounds/blob/master/scripts/background.js#L478

I also recall having made a jsfiddle at some point to compare in-extension context playback with normal web playback.

**Comment by freaktechnik** [comment]
And one more addition: the original sound is https://freesound.org/people/unfa/sounds/245645/ or https://github.com/freaktechnik/notification-sounds/blob/master/pop.flac as is used by the extension.

**Comment by zmike** [comment]
Ah, okay. I compared my sound against pop.flac, and the rate and channel count were different. Upon reencoding to match the default, it works fine.

I'd guess it should specify somewhere that the custom sound should be a 2 channel 48000hz flac format to be safe.

**Comment by freaktechnik** [comment]
Thanks again for pointing out that I should probably note the format of the default sound somewhere. I've now added it to https://discourse.mozilla.org/t/support-notification-sound/23758.
